<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="4" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-26T03:39:29 MYT" name="Suite" finished-at="2025-10-26T03:40:22 MYT" duration-ms="52810">
    <groups>
    </groups>
    <test started-at="2025-10-26T03:39:29 MYT" name="Test" finished-at="2025-10-26T03:40:22 MYT" duration-ms="52810">
      <class name="apiTest.apiTest1">
        <test-method signature="testCommentResponse()[pri:0, instance:apiTest.apiTest1@58a9760d]" started-at="2025-10-26T03:40:13 MYT" name="testCommentResponse" finished-at="2025-10-26T03:40:20 MYT" duration-ms="7519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCommentResponse -->
      </class> <!-- apiTest.apiTest1 -->
      <class name="UiTest.TestCase3">
        <test-method is-config="true" signature="setup()[pri:0, instance:UiTest.TestCase3@4e50c791]" started-at="2025-10-26T03:39:50 MYT" name="setup" finished-at="2025-10-26T03:39:55 MYT" duration-ms="4902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="incorrectPassword()[pri:0, instance:UiTest.TestCase3@4e50c791]" started-at="2025-10-26T03:39:55 MYT" name="incorrectPassword" finished-at="2025-10-26T03:39:55 MYT" duration-ms="386" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at UiTest.TestCase3.incorrectPassword(TestCase3.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectPassword -->
        <test-method is-config="true" signature="quitTest()[pri:0, instance:UiTest.TestCase3@4e50c791]" started-at="2025-10-26T03:39:55 MYT" name="quitTest" finished-at="2025-10-26T03:39:59 MYT" duration-ms="3504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitTest -->
      </class> <!-- UiTest.TestCase3 -->
      <class name="UiTest.TestCase2">
        <test-method is-config="true" signature="setup()[pri:0, instance:UiTest.TestCase2@1e66f1f5]" started-at="2025-10-26T03:39:41 MYT" name="setup" finished-at="2025-10-26T03:39:46 MYT" duration-ms="5079" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginWithLockedAccount()[pri:2, instance:UiTest.TestCase2@1e66f1f5]" started-at="2025-10-26T03:39:46 MYT" name="loginWithLockedAccount" finished-at="2025-10-26T03:39:47 MYT" duration-ms="391" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at UiTest.TestCase2.loginWithLockedAccount(TestCase2.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithLockedAccount -->
        <test-method is-config="true" signature="quitTest()[pri:0, instance:UiTest.TestCase2@1e66f1f5]" started-at="2025-10-26T03:39:47 MYT" name="quitTest" finished-at="2025-10-26T03:39:50 MYT" duration-ms="3361" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitTest -->
      </class> <!-- UiTest.TestCase2 -->
      <class name="UiTest.TestCase4">
        <test-method is-config="true" signature="setup()[pri:0, instance:UiTest.TestCase4@7530ad9c]" started-at="2025-10-26T03:39:59 MYT" name="setup" finished-at="2025-10-26T03:40:04 MYT" duration-ms="4882" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="completeCheckout()[pri:0, instance:UiTest.TestCase4@7530ad9c]" started-at="2025-10-26T03:40:04 MYT" name="completeCheckout" finished-at="2025-10-26T03:40:09 MYT" duration-ms="5780" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at UiTest.TestCase4.completeCheckout(TestCase4.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- completeCheckout -->
        <test-method is-config="true" signature="quitTest()[pri:0, instance:UiTest.TestCase4@7530ad9c]" started-at="2025-10-26T03:40:09 MYT" name="quitTest" finished-at="2025-10-26T03:40:13 MYT" duration-ms="3468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitTest -->
      </class> <!-- UiTest.TestCase4 -->
      <class name="UiTest.TestCase1">
        <test-method is-config="true" signature="setup()[pri:0, instance:UiTest.TestCase1@7d8704ef]" started-at="2025-10-26T03:39:30 MYT" name="setup" finished-at="2025-10-26T03:39:36 MYT" duration-ms="6842" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginSuccessful()[pri:0, instance:UiTest.TestCase1@7d8704ef]" started-at="2025-10-26T03:39:36 MYT" name="verifyLoginSuccessful" finished-at="2025-10-26T03:39:38 MYT" duration-ms="1073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginSuccessful -->
        <test-method is-config="true" signature="quitTest()[pri:0, instance:UiTest.TestCase1@7d8704ef]" started-at="2025-10-26T03:39:38 MYT" name="quitTest" finished-at="2025-10-26T03:39:41 MYT" duration-ms="3504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitTest -->
      </class> <!-- UiTest.TestCase1 -->
      <class name="apiTest.apiTest3">
        <test-method signature="testUserResponse()[pri:0, instance:apiTest.apiTest3@394df057]" started-at="2025-10-26T03:40:22 MYT" name="testUserResponse" finished-at="2025-10-26T03:40:22 MYT" duration-ms="325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserResponse -->
      </class> <!-- apiTest.apiTest3 -->
      <class name="apiTest.apiTest2">
        <test-method signature="postComment()[pri:0, instance:apiTest.apiTest2@71e9ddb4]" started-at="2025-10-26T03:40:20 MYT" name="postComment" finished-at="2025-10-26T03:40:22 MYT" duration-ms="1211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postComment -->
      </class> <!-- apiTest.apiTest2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
